environment:
  number: &num_envs 8 # Number of parallel environments
  game_name: "ALE/Breakout-v5" # Environment name
  seed: 7

encoder:
  speed_scale: 8.0
  num_envs: *num_envs
  max_objects: 32 # Maximum number of objects to encode for transformer / deepsets method
  use_rgb: false # Use RGB colors of objects
  use_category: false # Use object categories (paddle, ball, etc.) in the encoding

model:
  name: "PPO" # Model name (PPO or A2C)

  # Global parameters
  learning_rate: 0.0007 # Ignored if linear_scheduler is true
  gamma: 0.99
  scheduler: true # Use linear learning rate scheduler

  # Actor-Critic parameters (A2C and PPO)
  n_steps: 1024
  gae_lambda: 0.95
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  ppo_batch_size: 128 # PPO Only
  n_epochs: 8 # PPO Only
  clip_range: 0.3 # PPO Only, decaying linearly to 0.0


training:
  num_steps: 10000000 # Number of episodes to train