environment:
  number: &num_envs 16 # Number of parallel environments
  game_name: "BreakoutNoFrameskip-v4" # Environment name
  seed: 42

encoder:
  num_brick_layers: 6
  num_bricks_per_layer: 18
  bricks_y_start: 26.0 # y coord where the bricks begin to appear
  bricks_y_end: 62.0 # y coord where the bricks stop to appear
  frame_x_size: 160
  speed_scale: 10.0
  num_envs: *num_envs
  max_objects: 64 # Maximum number of objects to encode for transformer / deepsets method

model:
  name: "PPO" # Model name (PPO or A2C)

  # Global parameters
  learning_rate: 0.0001 # Ignored if linear_scheduler is true
  gamma: 0.99
  scheduler: true # Use linear learning rate scheduler
  lr_start: 0.001 # Initial learning rate
  lr_end: 0.00001 # Final learning rate
    
    # Actor-Critic parameters (A2C and PPO)
  n_steps: 2048
  gae_lambda: 0.95
  ent_coef: 0.0
  vf_coef: 0.5
  ppo_batch_size: 64 # PPO Only
  n_epochs: 10 # PPO Only


training:
  num_episodes: 5000000 # Number of episodes to train