environment:
  use_optimal_cores: false # Use optimal number of cores for parallel environments
  number: &num_envs 8 # Number of parallel environments
  game_name: "ALE/Breakout-v5" # Environment name
  seed: 14

encoder:
  speed_scale: 8.0
  num_envs: *num_envs
  max_objects: 32 # Maximum number of objects to encode for transformer / deepsets method

model:
  # Global parameters
  learning_rate: 0.0008 # Ignored if linear_scheduler is true
  gamma: 0.99
  scheduler: true # Use learning rate scheduler

  # PPO parameters
  n_steps: 256
  gae_lambda: 0.95
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  ppo_batch_size: 256
  n_epochs: 5
  clip_range: 0.3


training:
  num_steps: 10000000 # Number of episodes to train