environment:
  number: &num_envs 16 # Number of parallel environments
  game_name: "BreakoutNoFrameskip-v4" # Environment name
  seed: 42

encoder:
  speed_scale: 10.0
  num_envs: *num_envs
  max_objects: 64 # Maximum number of objects to encode for transformer / deepsets method

model:
  name: "PPO" # Model name (PPO or A2C)

  # Global parameters
  learning_rate: 0.0003 # Ignored if linear_scheduler is true
  gamma: 0.99
  scheduler: false # Use linear learning rate scheduler

  # Actor-Critic parameters (A2C and PPO)
  n_steps: 2048
  gae_lambda: 0.95
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  ppo_batch_size: 64 # PPO Only
  n_epochs: 10 # PPO Only
  clip_range: 0.2 # PPO Only


training:
  num_steps: 1000000 # Number of episodes to train