environment:
  use_optimal_cores: false # Automatially changes n_envs based on CPU cores
  number: &num_envs 8 # Number of parallel environments if use_optimal_cores is false
  game_name: "ALE/Breakout-v5" # Only use NoFrameskip versions
  seed: 42

encoder:
  speed_scale: 8.0
  num_envs: *num_envs
  max_objects: 32 # Maximum number of objects to encode for transformer / deepsets method
  use_rgb: false # Use RGB colors of objects
  use_category: false # Use object categories (paddle, ball, etc.) in the encoding

model:
  # Global parameters
  learning_rate: 0.0008  # Slightly reduced for more stable updates with more data
  gamma: 0.99
  scheduler: true # Use linear learning rate scheduler

  # Actor-Critic parameters (A2C and PPO)
  n_steps: 256
  gae_lambda: 0.95
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  ppo_batch_size: 256  # Increased: should be 1/8 to 1/32 of total rollout (16,384)
  n_epochs: 5  # Reduced: with more data per rollout, fewer epochs needed
  clip_range: 0.3

training:
  num_steps: 10000000 # Number of episodes to train