environment:
  number: 16 # Number of parallel environments
  game_name: "ALE/Breakout-v5"
  seed: 42

encoder:
  num_brick_layers: 6
  num_bricks_per_layer: 18
  bricks_start: 26 # y coord where the bricks begin to appear
  bricks_end: 62 # y coord where the bricks stop to appear
  frame_x_size: 160

model:
  feature_space_size: 113

optimizer:
  type: RMSProp # AdamW or RMSProp
  params:
    lr: 0.0007
    weight_decay: 0.00001 # AdamW only
    eps: 0.00001 # RMSProp only
    alpha: 0.99 # RMSProp only

training:
  max_updates: 156250 # about 50M steps
  steps_per_update: 20
  gamma: 0.99
  lambda: 0.95 # GAE lambda
  entropy_weight: 0.01
  actor_weight: 1.0
  critic_weight: 0.5
  update_frequency: 100