environment:
  use_optimal_cores: false # Automatially changes n_envs based on CPU cores
  number: &num_envs 8 # Number of parallel environments if use_optimal_cores is false
  game_name: "BreakoutNoFrameskip-v4" # Only use NoFrameskip versions
  seed: 42

encoder:
  speed_scale: 8.0
  num_envs: *num_envs
  max_objects: 32 # Maximum number of objects to encode for transformer / deepsets method
  use_rgb: false # Use RGB colors of objects
  use_category: false # Use object categories (paddle, ball, etc.) in the encoding
  use_events: false # Use events (collisions, etc.) in the encoding

model:
  # PPO Parameters
  PPO:
    learning_rate: 0.001  # Slightly reduced for more stable updates with more data
    gamma: 0.99
    scheduler: "exponential"  # Use exponential decay for learning rate
    n_steps: 256
    gae_lambda: 0.95
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 0.5
    ppo_batch_size: 256  # Increased: should be 1/8 to 1/32 of total rollout (16,384)
    n_epochs: 4  # Reduced: with more data per rollout, fewer epochs needed
    clip_range: 0.4

  # OCZero parameters
  OCZero:
    learning_rate: 0.001  # Slightly reduced for more stable updates with more data
    gamma: 0.99
    scheduler: "exponential"  # Use exponential decay for learning rate
    n_steps: 256
    gae_lambda: 0.95
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 0.5
    ppo_batch_size: 256  # Increased: should be 1/8 to 1/32 of total rollout (16,384)
    n_epochs: 4  # Reduced: with more data per rollout, fewer epochs needed
    clip_range: 0.4
    proj_coef: 1.0
    reward_pred_coef: 1.0

training:
  num_steps: 10000000 # Number of episodes to train